global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:8000"]
    metrics_path: /metrics

  - job_name: "checkout-service"
    static_configs:
      - targets: ["checkout-service:8001"]
    metrics_path: /metrics

  - job_name: "inventory-service"
    static_configs:
      - targets: ["inventory-service:8002"]
    metrics_path: /metrics

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
